object fobs: Tfobs
  Left = 63
  Top = 230
  BorderStyle = bsNone
  Caption = 'fobs'
  ClientHeight = 271
  ClientWidth = 240
  Color = clSkyBlue
  Font.Charset = ANSI_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  OnActivate = FormActivate
  PixelsPerInch = 96
  TextHeight = 13
  object SpeedButton1: TSpeedButton
    Left = 8
    Top = 224
    Width = 91
    Height = 33
    Caption = 'Confirma'
    Flat = True
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    Glyph.Data = {
      76010000424D7601000000000000760000002800000020000000100000000100
      04000000000000010000120B0000120B00001000000000000000000000000000
      800000800000008080008000000080008000808000007F7F7F00BFBFBF000000
      FF0000FF000000FFFF00FF000000FF00FF00FFFF0000FFFFFF00333333000000
      000033333377777777773333330FFFFFFFF03FF3FF7FF33F3FF700300000FF0F
      00F077F777773F737737E00BFBFB0FFFFFF07773333F7F3333F7E0BFBF000FFF
      F0F077F3337773F3F737E0FBFBFBF0F00FF077F3333FF7F77F37E0BFBF00000B
      0FF077F3337777737337E0FBFBFBFBF0FFF077F33FFFFFF73337E0BF0000000F
      FFF077FF777777733FF7000BFB00B0FF00F07773FF77373377373330000B0FFF
      FFF03337777373333FF7333330B0FFFF00003333373733FF777733330B0FF00F
      0FF03333737F37737F373330B00FFFFF0F033337F77F33337F733309030FFFFF
      00333377737FFFFF773333303300000003333337337777777333}
    NumGlyphs = 2
    ParentFont = False
    OnClick = SpeedButton1Click
  end
  object Panel1: TPanel
    Left = 8
    Top = 52
    Width = 223
    Height = 117
    BevelInner = bvRaised
    BevelOuter = bvLowered
    BevelWidth = 3
    BorderWidth = 2
    Color = clSkyBlue
    TabOrder = 0
    object btnobssete: TBitBtn
      Left = 131
      Top = 9
      Width = 20
      Height = 20
      Caption = '7'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 0
      OnClick = btnobsseteClick
    end
    object btnobsoito: TBitBtn
      Left = 151
      Top = 9
      Width = 20
      Height = 20
      Caption = '8'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 1
      OnClick = btnobsoitoClick
    end
    object btnobsnove: TBitBtn
      Left = 172
      Top = 9
      Width = 20
      Height = 20
      Caption = '9'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 2
      OnClick = btnobsnoveClick
    end
    object btnobsseis: TBitBtn
      Left = 111
      Top = 9
      Width = 20
      Height = 20
      Caption = '6'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 3
      OnClick = btnobsseisClick
    end
    object btnobscinco: TBitBtn
      Left = 91
      Top = 9
      Width = 20
      Height = 20
      Caption = '5'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 4
      OnClick = btnobscincoClick
    end
    object btnobsquatro: TBitBtn
      Left = 72
      Top = 9
      Width = 20
      Height = 20
      Caption = '4'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 5
      OnClick = btnobsquatroClick
    end
    object btnobstres: TBitBtn
      Left = 52
      Top = 9
      Width = 20
      Height = 20
      Caption = '3'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 6
      OnClick = btnobstresClick
    end
    object btnobsdois: TBitBtn
      Left = 32
      Top = 9
      Width = 20
      Height = 20
      Caption = '2'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 7
      OnClick = btnobsdoisClick
    end
    object btnobsHum: TBitBtn
      Left = 12
      Top = 9
      Width = 20
      Height = 20
      Caption = '1'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 8
      OnClick = btnobsHumClick
    end
    object btnobszero: TBitBtn
      Left = 192
      Top = 9
      Width = 20
      Height = 20
      Caption = '0'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 9
      OnClick = btnobszeroClick
    end
    object btnobslimpa: TBitBtn
      Left = 152
      Top = 69
      Width = 60
      Height = 20
      Caption = 'LIMPA'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 10
      OnClick = btnobslimpaClick
    end
    object btnobsQ: TBitBtn
      Left = 12
      Top = 29
      Width = 20
      Height = 20
      Caption = 'Q'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 11
      OnClick = btnobsQClick
    end
    object btnobsW: TBitBtn
      Left = 32
      Top = 29
      Width = 20
      Height = 20
      Caption = 'W'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 12
      OnClick = btnobsWClick
    end
    object btnobsE: TBitBtn
      Left = 52
      Top = 29
      Width = 20
      Height = 20
      Caption = 'E'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 13
      OnClick = btnobsEClick
    end
    object btnobsR: TBitBtn
      Left = 72
      Top = 29
      Width = 20
      Height = 20
      Caption = 'R'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 14
      OnClick = btnobsRClick
    end
    object btnobsT: TBitBtn
      Left = 92
      Top = 29
      Width = 20
      Height = 20
      Caption = 'T'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 15
      OnClick = btnobsTClick
    end
    object btnobsY: TBitBtn
      Left = 112
      Top = 29
      Width = 20
      Height = 20
      Caption = 'Y'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 16
      OnClick = btnobsYClick
    end
    object btnobsU: TBitBtn
      Left = 132
      Top = 29
      Width = 20
      Height = 20
      Caption = 'U'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 17
      OnClick = btnobsUClick
    end
    object btnobsI: TBitBtn
      Left = 152
      Top = 29
      Width = 20
      Height = 20
      Caption = 'I'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 18
      OnClick = btnobsIClick
    end
    object btnobsO: TBitBtn
      Left = 172
      Top = 29
      Width = 20
      Height = 20
      Caption = 'O'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 19
      OnClick = btnobsOClick
    end
    object btnobsP: TBitBtn
      Left = 192
      Top = 29
      Width = 20
      Height = 20
      Caption = 'P'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 20
      OnClick = btnobsPClick
    end
    object btnobsA: TBitBtn
      Left = 12
      Top = 49
      Width = 20
      Height = 20
      Caption = 'A'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 21
      OnClick = btnobsAClick
    end
    object btnobsS: TBitBtn
      Left = 32
      Top = 49
      Width = 20
      Height = 20
      Caption = 'S'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 22
      OnClick = btnobsSClick
    end
    object btnobsD: TBitBtn
      Left = 52
      Top = 49
      Width = 20
      Height = 20
      Caption = 'D'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 23
      OnClick = btnobsDClick
    end
    object btnobsF: TBitBtn
      Left = 72
      Top = 49
      Width = 20
      Height = 20
      Caption = 'F'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 24
      OnClick = btnobsFClick
    end
    object btnobsG: TBitBtn
      Left = 92
      Top = 49
      Width = 20
      Height = 20
      Caption = 'G'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 25
      OnClick = btnobsGClick
    end
    object btnobsH: TBitBtn
      Left = 112
      Top = 49
      Width = 20
      Height = 20
      Caption = 'H'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 26
      OnClick = btnobsHClick
    end
    object btnobsJ: TBitBtn
      Left = 132
      Top = 49
      Width = 20
      Height = 20
      Caption = 'J'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 27
      OnClick = btnobsJClick
    end
    object btnobsK: TBitBtn
      Left = 152
      Top = 49
      Width = 20
      Height = 20
      Caption = 'K'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 28
      OnClick = btnobsKClick
    end
    object btnobsL: TBitBtn
      Left = 172
      Top = 49
      Width = 20
      Height = 20
      Caption = 'L'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 29
      OnClick = btnobsLClick
    end
    object btnobsCEDILHA: TBitBtn
      Left = 192
      Top = 49
      Width = 20
      Height = 20
      Caption = #199
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 30
      OnClick = btnobsCEDILHAClick
    end
    object btnobsZ: TBitBtn
      Left = 12
      Top = 69
      Width = 20
      Height = 20
      Caption = 'Z'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 31
      OnClick = btnobsZClick
    end
    object btnobsX: TBitBtn
      Left = 32
      Top = 69
      Width = 20
      Height = 20
      Caption = 'X'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 32
      OnClick = btnobsXClick
    end
    object btnobsC: TBitBtn
      Left = 52
      Top = 69
      Width = 20
      Height = 20
      Caption = 'C'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 33
      OnClick = btnobsCClick
    end
    object btnobsV: TBitBtn
      Left = 72
      Top = 69
      Width = 20
      Height = 20
      Caption = 'V'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 34
      OnClick = btnobsVClick
    end
    object btnobsB: TBitBtn
      Left = 92
      Top = 69
      Width = 20
      Height = 20
      Caption = 'B'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 35
      OnClick = btnobsBClick
    end
    object btnobsN: TBitBtn
      Left = 112
      Top = 69
      Width = 20
      Height = 20
      Caption = 'N'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 36
      OnClick = btnobsNClick
    end
    object btnobsM: TBitBtn
      Left = 132
      Top = 69
      Width = 20
      Height = 20
      Caption = 'M'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 37
      OnClick = btnobsMClick
    end
    object btnobsSPACE: TBitBtn
      Left = 12
      Top = 89
      Width = 200
      Height = 20
      Caption = 'ESPACO'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 38
      OnClick = btnobsSPACEClick
    end
  end
  object GroupBox1: TGroupBox
    Left = 8
    Top = 8
    Width = 223
    Height = 38
    Caption = 'Observa'#231#227'o'
    TabOrder = 1
    object Eobs: TEdit
      Left = 4
      Top = 13
      Width = 212
      Height = 21
      TabOrder = 0
    end
  end
end
